Repository FRCTeam3255/2024_Offbot_Code, pull requests merged in 2024-08, with the labels that each got.

#9 Limelight Implementation
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AddVisionMeasurement.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/Limelight.java
  src/main/java/frc/robot/subsystems/Shooter.java
  vendordeps/SuperCORE.json
Labels: Tested

#16 Update README.md to match 2024_Robot_Code
  README.md
  src/main/assets/FRC_SocialDLC_FB_Post.png
Labels: urgent

#18 Update README.md
  README.md
Labels: urgent

#19 Add Beam Break Sensor
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/subsystems/Transfer.java
Labels: Tested

#15 started state machine
  simgui-ds.json
  simgui.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/Drive.java
  src/main/java/frc/robot/commands/States/Ejecting.java
  src/main/java/frc/robot/commands/States/Intaking.java
  src/main/java/frc/robot/commands/States/NoneState.java
  src/main/java/frc/robot/commands/States/PrepShuffle.java
  src/main/java/frc/robot/commands/States/PrepSpeaker.java
  src/main/java/frc/robot/commands/States/StoreFeeder.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/Intake.java
  src/main/java/frc/robot/subsystems/StateMachine.java
  src/main/java/frc/robot/subsystems/Transfer.java
Labels: Tested in Simulation
